# Generated by Django 4.1.5 on 2023-02-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nebiti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nebiti.voter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(name="post", options={"ordering": ["-id"]},),
        migrations.RenameField(
            model_name="post", old_name="content", new_name="description",
        ),
        migrations.RemoveField(model_name="post", name="dislikes",),
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(name="Reaction",),
        migrations.AddField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nebiti.post"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nebiti.voter"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="votes",
            field=models.ManyToManyField(through="nebiti.Vote", to="nebiti.voter"),
        ),
    ]
