# Generated by Django 4.1.5 on 2023-02-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nebiti", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="delegated_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegate_of",
                to="nebiti.voter",
            ),
        ),
    ]
