# Generated by Django 4.1.5 on 2023-02-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nebiti", "0004_alter_voter_delegate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="delegated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegate_of",
                to="nebiti.voter",
            ),
        ),
    ]
